spring.application.name=URECLiveBackend

# PostgreSQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}


# Server Configuration
server.address=0.0.0.0
server.port=${PORT:8080}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refreshExpiration=${JWT_REFRESH_EXPIRATION:604800000}
